name: multipleHardcoreLives
version: '0.1'
author: Dim_Toups
main: org.mhl.multiplehardcorelives.MultipleHardcoreLives
api-version: '1.20'

permissions:
  startSession:
    default: true
  endSession:
    default: true

commands:
  session:
    description: Manages sessions across the server
    usage: /session [start | end]
    permission: admin.manage.playerpermission
  player:
    description: Manages and displays informations about players
    usage: /player [list | infos | setLives] [player name] [number of lives]
    permission: admin.manage.playerpermission
  server:
    description: Manages and displays informations about the server
    usage: /server [reset | defaultNumberOfLives] [lives]
    permission: admin.manage.playerpermission
  writeChanges:
    description: Writes changes in the database
    usage: /writeChanges
    permission: admin.manage.playerpermission
  verify:
    description: Verify data from the plugin
    usage: /verify [server]
    permission: admin.manage.playerpermission
  mhlWorldBorder:
    description: Manages and displays informations about the world border
    usage: /mhlWorldBorder [length | reload] [length]
    permission: admin.manage.playerpermission